version: '3'

services:
  users-service:
    container_name: users_service
    build: ./users-service
    command: npx nodemon index.js
    depends_on: 
      - db
    volumes:
      - ./users-service:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  db:
    container_name: users_db
    image: mongo
    ports:
      - "27017:27017"
